### ISSUE TITLE
"S" now has to be explicitly mapped

### ISSUE THREAD

**Issue by mon10a** [justinmk/vim-sneak#142] opened 2015-05-30 19:49 UTC
I just updated from 1.7.2 to 1.7.4 and noticed that "S" is no longer mapped to Sneak/Streak reverse. "S" is back to Vim's original delete line and enter insert mode.

I can manually fixe by putting 
    nmap S <Plug>(SneakStreakBackward)
in my .vimrc, but was wondering whether this was an intentional change.

I'm using MacVim 7.4 (patches 1-622).

Thanks.

**Comment by justinmk** [comment] 2015-05-30 21:03
I can't reproduce that issue. 

Seems like sneak is detecting some other mapping on `S` and therefore isn't auto-mapping it (maybe when you updated your plugins?).

Here's a quick way to test without other plugins:

    vim -u NONE -N -c ':set runtimepath+=~/.vim/bundle/vim-sneak/' -c ':runtime plugin/sneak.vim'

**Comment by justinmk** [comment] 2015-05-30 21:05
`call sneak#debug#report()` may also be useful.

**Comment by anthoq88** [comment] 2016-01-03 18:16
Hi,
I'm having the same issue.

I tried using vim without any other plugins (using your command) and still did not have S mapped to sneak backwards.

Here is the output of my `call sneak#debug#report`:

```

NVIM 0.1.1 (compiled Dec  8 2015 21:15:50)
Commit: 6d583f85875499fbe05b549a1c0ac57b9ededd3d
Build type: Dev
Compilation: /usr/local/Library/ENV/4.3/clang -Wconversion -O2 -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -I/tmp/neovim20151208-40034-1x9qkrk/build/config -I/tmp/neovim20151208-40034-1x9qkrk/src -I/tmp/neovim20151208-40034-1x9qkrk/deps-build/usr/include -I/tmp/neovim20151208-40034-1x9qkrk/deps-build/usr/include -I/tmp/neovim20151208-40034-1x9qkrk/deps-build/usr/include/luajit-2.0 -I/tmp/neovim20151208-40034-1x9qkrk/deps-build/usr/include -I/tmp/neovim20151208-40034-1x9qkrk/deps-build/usr/include -I/tmp/neovim20151208-40034-1x9qkrk/deps-build/usr/include -I/tmp/neovim20151208-40034-1x9qkrk/deps-build/usr/include -I/usr/local/opt/gettext/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/usr/include -I/tmp/neovim20151208-40034-1x9qkrk/build/src/nvim/auto -I/tmp/neovim20151208-40034-1x9qkrk/build/include

has("autocmd")=1
&magic=1
&buftype=
&virtualedit=
&ignorecase=0
&smartcase=1
&background=dark
&keymap=
g:mapleader= 

defined:     sneak#to
defined:     sneak#rpt
defined:     sneak#search#new
defined:     sneak#hl#removehl
defined:     sneak#util#echo

sneak#opt: {'streak': 0, 'use_ic_scs': 0, 'absolute_dir': 0, 'map_netrw': 1, 'streak_esc': ' ', 'textobject_z': 1, 't_reset': 1, 'f_reset': 1, 's_next': 0, 'prompt': '>'}

x  f           * sneak#reset('f')
	Last set from ~/.config/nvim/plugged/vim-sneak/plugin/sneak.vim
n  f           * sneak#reset('f')
	Last set from ~/.config/nvim/plugged/vim-sneak/plugin/sneak.vim

x  F           * sneak#reset('F')
n  F           * sneak#reset('F')

x  t           * sneak#reset('t')
n  t           * sneak#reset('t')

x  T           * sneak#reset('T')
n  T           * sneak#reset('T')

x  s             <Plug>Sneak_s
n  s             <Plug>Sneak_s

x  S             <Plug>VSurround

o  z             <Plug>Sneak_s

x  Z             <Plug>Sneak_S
o  Z             <Plug>Sneak_S

x  ;             <Plug>SneakNext
o  ;             <Plug>SneakNext
n  ;             <Plug>SneakNext
```

I'm using neovim 0.1.1

**Comment by justinmk** [comment] 2016-01-04 03:04
@anthoq88 Thanks for the report. Based on [this line](https://github.com/justinmk/vim-sneak/blob/c6243c4b1a7ad1464440ac70f5abb1f902b748d7/plugin/sneak.vim#L344) you can see that this can only happen under 3 possible conditions.

Can you check the following:

```
:echo hasmapto('<Plug>SneakBackward')
:echo hasmapto('<Plug>Sneak_S', 'n')
:echo mapcheck('S', 'n')
```

Closing this pre-emptively, but I will be notified if you reply.

**Closed by justinmk** 2016-01-04 03:04 UTC
Labels: waiting

**Comment by justinmk** [comment] 2016-01-04 03:14
Also what is your full sneak config, if any?

**Comment by bounceme** [comment] 2016-02-27 08:18
I also had this issue and found that using vim-yankstack with the setup function causes it
https://github.com/maxbrunsfeld/vim-yankstack#compatibility

**Comment by justinmk** [comment] 2016-02-27 15:46
@bounceme Thanks for the note. After https://github.com/neovim/neovim/pull/4304 yankstack won't be needed ;)

**Comment by bfredl** [comment] 2016-02-28 15:49
well, to be clear, you still "need" a plugin like yankstack but these plugins could be improved to not override yank mappings after neovim/neovim#4304
